### ISSUE TITLE
Make the rocket slow down if not accelerated (friction forces or something, even though there is no air in space, there must be some force that slows it down... right?)

### ISSUE THREAD

**Issue by SilviuShader** [AstroSpiders/The-Astro-Spider#2]

**Comment by BaraTudor2025** [comment]
Am putea sa aplicam forta de frictiune abia cand se apropie de planeta, si zicem ca aia-i atmosfera. De distanta oricum avem nevoie in formula cu gravitatie, si cand trece de un o valoare fixa, aplicam si Ff ul

**Comment by SilviuShader** [comment]
pai aia e gravitatia, pt gravitatie e alt ticket. 
Pt ticket-ul asta e vorba cand racheta e destul de departe de planete... ca nah, nu ai frane pe racheta, deci daca nu e oprita de "atmosfera" cumva, nu prea ai ce sa-i faci

**Comment by BaraTudor2025** [comment]
N avem frane, dar nu intoarcem racheta cu propulsorul spre planeta? Si in timp ce cade mai da din thruster ca sa incetineasca. Cum face SpaceX

**Comment by SilviuShader** [comment]
dap, asta la aterizare.
bine, inteleg argumentul, cum ca atunci cand nu suntem in apropierea unei planete nu prea avem motiv de incetinire... dar tot e mai greu de manevrat asa... trebuie sa fie pe acolo ceva forta care sa incetineasca racheta, macar putin cat timp nu e aproape de o planeta.

**Comment by SilviuShader** [comment]
Acum la cum e codata, teoretic poate accelera la infinit, nu cred e posibil asa ceva nici irl.
La masini e imposibil pt ca ai frecarea cu aerul... aici nu ai aer, dar tot cred ca e ceva forta de frecare care intervine si nu te lasa sa accelerezi la infinit.
